name: sample-app
baseDomain: realhandsonlabs.net
replicas: 1

namespace: development

aws:
  region: us-east-1

image:
  repository: lakeside763/school-mgt
  tag: latest
  pullPolicy: IfNotPresent

deployment:
  name: sample-app-depl
  containerPort: 3000
  containerName: sample-app-container

service:
  name: sample-app-svc
  servicePort: 433

ingress:
  name: sample-app-ingress

configMap:
  name: sample-app-configmap

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}