apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sample-eks
  region: us-east-1
  version: "1.27"

vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: HighlyAvailable

managedNodeGroups:
- name: sample-eks-node-group
  instanceType: t2.small
  desiredCapacity: 1
  privateNetworking: true

availabilityZones: ["us-east-1a", "us-east-1b"]