apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "sample-app.name" . }}
    chart: {{ template "sample-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "sample-app.name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.servicePort }}
    targetPort: {{ .Values.deployment.containerPort }}
  type: NodePort