apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    chart: {{ .Chart.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.servicePort }}
    targetPort: {{ .Values.deployment.containerPort }}
  type: NodePort